### ISSUE TITLE
Configure user/password for neo4j client in app and environment

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/prov-service#12]
@Pawel-Madej I can't seem to figure out how to configure Neo4j credentials such that the app works locally _and_ within a TravisCI build environment.

My latest attempt to update the main password includes this section of `synprov/config.py`:

```python
neomod = NeoModel(connex_app.app, variables={
    'user': 'neo4j',
    'password': 'mypassword',
    'host': neo4j_host,
    'port': 7687
})
```

... and this command in `.travis.yml`:
```yaml
  - neo4j-admin set-initial-password mypassword
```

However, I still get an authentication error during the build:
```
$ neo4j-admin set-initial-password mypassword
Changed password for user 'neo4j'.
$ synprov
Failed: The client is unauthorized due to authentication failure.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/synprov", line 7, in <module>
    from synprov.__main__ import main
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/synprov/__main__.py", line 5, in <module>
    from synprov import config
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/synprov/config.py", line 18, in <module>
    'port': 7687
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/flask_neomodel.py", line 28, in __init__
    self.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/flask_neomodel.py", line 51, in connect
    self.retry()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/flask_neomodel.py", line 66, in retry
    raise ValueError('No connection available')
ValueError: No connection available
The command "synprov" exited with 1.
```

I feel like there should be a better way to manage credentials (e.g., with environment variables or some sort of config file), but I'm having a hard time finding examples. Do you have any experience installing and configuring Neo4j within Travis (or for production deployments)?

**Comment by Pawel-Madej** [comment]
@jaeddy 
to change password and user name for Neo4j, I'm using following script:
`
#!/bin/bash

DEFAULT_IFS="$IFS"
SALT_LEN=32

# either read from stdin or use the argument
if [ -z "$1" ]; then
  read INPUT
else
  INPUT="$1"
fi

if [ -z "$INPUT" ]; then
 echo "correct format <uname:pass>"
 exit
fi

IFS=':'
read -a UNAME_PASS <<< "$INPUT"

UNAME="${UNAME_PASS[0]}"
PASS="${UNAME_PASS[1]}"

# representing the password in hex format like \xAB\x0C etc
# HEX_PASS=$(echo -n $PASS | xxd -p | awk '{print toupper($1);}' | sed -r 's/(.{2})/\\x\1/g')
HEX_PASS=$(echo -n $PASS | hexdump -v -e '"\\\x" 1/1 "%02X"')
# echo $HEX_PASS


# create the salt and store it in hex format
SALT=$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w $SALT_LEN | head -n 1)
# SALT="28FD26AD92D6D2D8820E969F3F3732B4"
HEX_SALT=$(echo -n $SALT | sed -r 's/(.{2})/\\x\1/g')


# calculate the sha256 sum of the salt and password value
# need to split the output because the output ends with a hyphen
IFS=' '
read -a PASSWORD_HASH_ARRAY <<< $(printf $HEX_SALT$HEX_PASS | sha256sum)
PASSWORD_HASH="${PASSWORD_HASH_ARRAY[0]}"

# echo "$UNAME;$PASS;$SALT"
# echo "$PASSWORD_HASH"

# and print out the auth string
COMBINED=$(echo -n "$PASSWORD_HASH,$SALT" | awk '{print toupper($1);}')
echo "$UNAME:SHA-256,$COMBINED:"

IFS="$DEFAULT_IFS"
`

**Comment by Pawel-Madej** [comment]
@jaeddy 

1. To change username and password I'm using `build_auth_string.sh` script (added to master branch in this repo). It works like this:
- go to folder `/var/lib/neo4j/data/dbms/`. It should contain `auth` file, which actually contain hashed Neo4j user login and password. 
- upload build_auth_string.sh script into this folder (or create a file with this script). Remember to change permission to be able to execute this script.
- run script like that: `build_auth_string.sh myUsername:myP@ssw0rd`
It worked for in my case, but I was not verifying it with Travis.

2. I'm usually creating environment variables to handle credential, which later on are read in the script, eg.
- export NEO4J_USERNAME='neo4j'
- export NEO4J_PASSWORD='password'

3. Not recommended, but should be possible to disable authentication, by:
- edit `$NEO4J_HOME/conf/neo4j.conf` file
- change line as follows
`# Whether requests to Neo4j are authenticated.
# To disable authentication, uncomment this line
dbms.security.auth_enabled=false`

**Comment by jaeddy** [comment]
Thanks, @Pawel-Madej! I like the idea of using environment variables, just couldn't quite figure out how to change the password programmatically. I'll give it a try with your script and update the Travis config.

**Comment by jaeddy** [comment]
Everything seems to be working in Travis now. #9 should be ready for review.
